### ISSUE TITLE
`connect_#key_changed` ergonomics could be improved

### ISSUE THREAD

**Issue by RealKC** [SeaDve/gsettings-macro#2]
Currently the closure passed in to `connect_#key_changed` functions must be a `Fn(&gio::Settings)` closure, however this isn't nice as you lose all the benefits of this macro once you're inside that closure.

This is a snippet from my project where I use your macro

```rust
            settings.connect_is_history_enabled_changed(clone!(@strong stack => move |settings| {
                    let is_history_enabled = settings.boolean("is-history-enabled");
                    if is_history_enabled {
                        stack.set_visible_child_name("image-grid");
                    } else {
                        stack.set_visible_child_name("message");
                    }
            }));
```

and I don't really like it.

I think making it be `Fn(&GeneratedSettingsStruct)`, or `Fn(&GeneratedSettingsStruct, TypeOf#key)` would improve its ergonomics.

**Comment by SeaDve** [comment]
Oh yeah, that makes sense. Changed the func parameter to `Fn(&GeneratedSettingsStruct)`

**Comment by SeaDve** [comment]
I btw made a release with the fix

**Comment by RealKC** [comment]
I saw :), planning on making use of it later
